variables:
  VERSION: "${CI_BUILD_REF_NAME}"

stages:
- build

build:
  stage: build
  script:
  #    Handy for debugging
  - whoami
  - hostname
  - pwd

  - echo "Distribution file name is '${FILENAME}'"
  - echo "The branch or tag name for this project built is '${VERSION}'"

  - FILENAME_VERSION=${VERSION}"_rcsb-json-schema.tgz"
  - echo "Latest versioned file name ${FILENAME_VERSION}"

  - mvn -v

  #    Build via maven
  - mvn --batch-mode --errors -U clean package

  #    See results (size)
  - cd target
  - ls -alh *

  #    Tar the built files (jar + dependencies)
  - echo "We will build a tar file called [${FILENAME_VERSION}]"
  - tar -czvf ${FILENAME_VERSION}
  - ls -alh ${FILENAME_VERSION}

#    Send artifacts to the build locker
  - sshpass -p 3ffd8b48e7ed9f sftp transporter@bl-receive.rcsb.org:5-schema <<< $"put ../${FILENAME_VERSION}"
  - echo "Sent ${FILENAME_VERSION} to the build locker"

  tags:
  - Java8-Nexus3
