variables:
  VERSION: "${CI_BUILD_REF_NAME}"
  FILENAME: "dw_source_schemas"
  FILE_EXT: "tar.gz"

stages:
  - build

build:
  stage: build
  script:
#    Handy for debugging
    - whoami
    - hostname
    - pwd

    - echo "Distribution file name is '${FILENAME}'"
    - echo "The branch or tag name for this project built is '${VERSION}'"

    - FILENAME_VERSION=${FILENAME}"_"${VERSION}"."${FILE_EXT}
    - echo "Latest versioned file name ${FILENAME_VERSION}"

#    Produce distribution of latest schemas
    - echo "Will create ${FILENAME_VERSION}"
    - tar -cvzf ../${FILENAME_VERSION} schemas/

#    Send artifacts to the build locker
    - sshpass -p 3ffd8b48e7ed9f sftp transporter@bl-receive.rcsb.org:5-schema <<< $"put ../${FILENAME_VERSION}"
    - echo "Sent ${FILENAME_VERSION} to the build locker"

  tags:
  - Java8-Nexus3