variables:
  BRANCH: "${CI_BUILD_REF_NAME}"
  FILENAME: "dw_source_schemas"
  FILE_EXT: "tar.gz"

stages:
  - build

build:
  stage: build
  script:
#    Handy for debugging
    - whoami
    - hostname
    - pwd

    - VERSION=$(git describe --tags --abbrev=0)
    - echo "Distribution file name ${FILENAME}"
    - echo "Current branch name ${BRANCH}"
    - echo "Latest version (latest git tag) ${VERSION}"

    - FILENAME_VERSION=${FILENAME}"_"${VERSION}"."${FILE_EXT}
    - echo "Latest versioned file name ${FILENAME_VERSION}"

    - FILENAME_LATEST=${FILENAME}"_latest_"${BRANCH}"."${FILE_EXT}
    - echo "Latest snapshot file name ${FILENAME_LATEST}"

#    Produce distribution of latest snapshot schemas
    - cd ..
    - echo "Will create ${FILENAME_LATEST}"
    - tar -cvzf ${FILENAME_LATEST} rcsb-json-schema/schemas/

#    Send artifacts as latest to build locker
    - sshpass -p 3ffd8b48e7ed9f sftp transporter@bl-receive.rcsb.org:5-schema <<< $"put ${FILENAME_LATEST}"
    - echo "Sent ${FILENAME_LATEST} to the build locker"

#    Produce distribution of latest versioned schemas
    - cd rcsb-json-schema
    - git checkout tags/${VERSION}
    - cd ..
    - echo "Will create ${FILENAME_VERSION}"
    - tar -cvzf ${FILENAME_VERSION} rcsb-json-schema/schemas/

#    Send artifacts to the build locker
    - sshpass -p 3ffd8b48e7ed9f sftp transporter@bl-receive.rcsb.org:5-schema <<< $"put ${FILENAME_VERSION}"
    - echo "Sent ${FILENAME_VERSION} to the build locker"

  tags:
  - Java8-Nexus3