variables:
  VERSION: "${CI_BUILD_REF_NAME}"

stages:
- build

build:
  stage: build
  script:
  #    Handy for debugging
  - whoami
  - hostname
  - pwd

  #    Build via maven
  - mvn -v
  - VERSION_NAME=${VERSION}"-SNAPSHOT"
  - echo "JSON schemas build version "${VERSION_NAME}
  - mvn --batch-mode --errors -U -Drevision=${VERSION_NAME} clean deploy

  only:
    - branches

  tags:
  - Java8-Nexus3
