name: Schema and full stack release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Schema Major version'
        type: string
        required: true
      minor:
        description: 'Schema Minor version'
        type: string
        required: true
      patch:
        description: 'Schema Patch version'
        type: string
        required: true


env:
  NEW_SCHEMA_VERSION: "${{ inputs.major }}.${{ inputs.minor }}.${{ inputs.patch }}"

jobs:
  release-rcsb-json-schemas:
    runs-on:
      - self-hosted
      - java
    steps:
      - uses: actions/checkout@v3
      - name: Setup git author information
        run: |
          git config user.name RCSBSystem
          git config user.email it@rcsb.org
      - run: mvn --version
      - name: Set version
        run: mvn versions:set -DnewVersion=$NEW_SCHEMA_VERSION --no-transfer-progress
      - name: Commit and tag new version
        run: |
          git add pom.xml
          git commit -m "[actions] Updated version in pom.xml to $NEW_SCHEMA_VERSION"
          git tag $NEW_VERSION
      - name: Publish to nexus via maven deploy
        run: mvn --batch-mode --errors -U clean deploy
      - name: Increment version for next dev cycle
        run: |
          NEXT_PATCH=$(mvn build-helper:parse-version help:evaluate -Dexpression=parsedVersion.nextIncrementalVersion -q -DforceStdout --no-transfer-progress)
          mvn versions:set -DnewVersion="${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.$NEXT_PATCH-SNAPSHOT" -DallowSnapshots --no-transfer-progress
      - name: Commit new version for next dev cycle
        run: |
          git add pom.xml
          git commit -m "[actions] Next development cycle"
      - name: Push back to GitHub
        run: git push --all
  update-mojave-model:
    uses: rcsb/devops-cicd-github-actions/.github/workflows/update-schema-dependency-version.yaml@master
    with:
      schema-version: $NEW_SCHEMA_VERSION
      downstream-repo-to-update: rcsb-mojave-model
      schema-property-name-in-repo: rcsb-json-schema.version
# TODO mojave-model needs building and publishing to nexus on tag creation. How to wait for that?
  update-downstreams:
    strategy:
      matrix:
        repos: [rcsb-redwood, rcsb-yosemite, rcsb-shape, rcsb-borrego, rcsb-everglades]
    uses: rcsb/devops-cicd-github-actions/.github/workflows/update-schema-dependency-version.yaml@master
    with:
      schema-versiom: $NEW_SCHEMA_VERSION
      downstream-repo-to-update: ${{ matrix.repos }}
      schema-property-name-in-repo: rcsb.mojave.model.version

